# Generated by Django 5.2.14 on 2026-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-opened_at'],
            },
        ),
    ]
